[package]
name = "parsing-example"
version = "0.1.0"
license = "MIT OR Apache-2.0"

edition.workspace = true
rust-version.workspace = true

publish = false # Standalone example; should not be published

[dependencies]
arson-parse = { path = "../../crates/arson-parse", features = ["reporting"] }
