max_width = 120
chain_width = 60
struct_lit_width = 50
use_small_heuristics = "Default"

match_block_trailing_comma = true

# group_imports = "StdExternalCrate"
# imports_granularity = "Module"

# hex_literal_case = "Upper"
