[package]
name = "hello-world"
version = "0.2.0"
license = "MIT OR Apache-2.0"

edition.workspace = true
rust-version.workspace = true

publish = false # Standalone example; should not be published

[dependencies]
arson = { path = "../../crates/arson" }
