[package]
name = "arson-testapp"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false # Standalone test application; should not be published

[dependencies]
arson = { version = "0.1.0", path = "../arson" }
