[package]
name = "arson-fmtlib"

version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

publish = false

[dependencies]
arson-parse = { path = "../../crates/arson-parse" }

thiserror = "1.0.65"
