[package]
name = "arson-dtb"

version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

publish = false

[dependencies]
arson-parse = { path = "../../crates/arson-parse", features = ["encoding"] }

byteorder = "1.5.0"
thiserror = "1.0.65"
