[package]
name = "arson-fs"
version = "0.1.0"
edition.workspace = true
license.workspace = true

publish = false

[dependencies]
arson-core = { version = "0.1.0", path = "../arson-core" }
thiserror = "1.0.65"
