[package]
name = "arson-fs"

version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

publish = false

[dependencies]
arson-core = { version = "0.1.0", path = "../arson-core" }
thiserror = "1.0.65"
